### ISSUE TITLE
Doesn't launch.

### ISSUE THREAD

**Issue by strife98** [MythicManiac/MythicModManager#3]
I've made sure it's a clean unmodified folder I've even moved the installation back to C drive to see if maybe that would fix it, but unfortunately nothing has. Whenever I launch it, it hangs for a bit before coming up with the attatched image and then crashing out really quickly. I had to time getting this window before it disappeared. 
![error](https://user-images.githubusercontent.com/23270274/56686344-c73de180-66a1-11e9-90f6-bbd68dca6ffd.png)

**Comment by MythicManiac** [comment]
Hey,

This seems like an issue in your `config.json` file, which to seems to be in an invalid format. Json files require double backslashes (`\\`) instead of a single one, in cases that's what is tripping it up.

**Comment by strife98** [comment]
Ah yup, that worked. Didn't know that was a thing. Thank you!

**Comment by MythicManiac** [comment]
Great to hear it worked for you 👍
